### ISSUE TITLE
Suggestion [.INC file related]

### ISSUE THREAD

**Issue by ClaudiuHKS** [peace-maker/DHooks2#4]
``native bool DHookSetFromConf(Handle setup, Handle gameconf, SDKFuncConfSource source, const char[] name);``

IIRC, ``SDKFuncConfSource`` needs ``sdktools.inc`` see https://sm.alliedmods.net/new-api/sdktools/SDKFuncConfSource

I suggest to edit the .INC file doing something about this. Either ``#include <sdktools>`` or ``#tryinclude <sdktools>`` + ``#if defined (_..._included) /* ... */ #endif``.

Thanks for your great work though!

**Comment by peace-maker** [comment]
I didn't include something like this yet, since I thought it would obscure dependencies in plugins. Like only wanting an optional dependency on dhooks, but a strong dependency on sdktools. Thinking about it now, adding `#include <sdktools>` to the dhooks include file wouldn't hurt this at all.

You could still manually include sdktools before dhooks in your plugin and thus only include dhooks without `REQUIRE_EXTENSIONS`. DHooks itself requires bintools, sdktools and sdkhooks to be running to load up, so only wanting dhooks and not sdktools is not even possible.

I don't know what I was thinking when adding the `DHookSetFromConf` native, but it seemed like a good reason to not include sdktools back then. I guess we can just add it now.

**Comment by peace-maker** [comment]
`#include <sdktools>` is in the include file now.
